etl_transform:
  input: data/raw/data.csv
  output: data/processed/data.csv

etl_load:
  input: data/processed/data.csv
  # DATABASE INFORMATION

model_train:
  model_path: models/logistic_regression.pkl
  artifact_path: artifacts
